# Generated by Django 4.2.11 on 2024-03-16 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofileseemodel_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentuploud_model',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
