# Generated by Django 4.2.11 on 2024-03-16 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofileseemodel_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(null=True, related_name='commnetrion_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentuploud_model',
            name='viewer',
            field=models.PositiveIntegerField(default=1, verbose_name=()),
            preserve_default=False,
        ),
    ]
