# Generated by Django 4.2.11 on 2024-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment_like_contentuploud_model_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentuploud_model',
            name='viewer',
            field=models.PositiveIntegerField(null=True, verbose_name=()),
        ),
    ]
