# Generated by Django 4.2.11 on 2024-03-17 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contentuploud_model_content_title_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTofrined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for_add_to_fried', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
