# Generated by Django 4.2.11 on 2024-03-17 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_addtofrined'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtofrined',
            name='add_to_friend',
            field=models.ManyToManyField(related_name='add_user_to_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
