# Generated by Django 4.2.11 on 2024-03-17 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofileseemodel_add_to_friend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFiend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_friend', models.ManyToManyField(related_name='adding_user_to_frien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.addfiend'),
        ),
    ]
