# Generated by Django 4.2.11 on 2024-03-17 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofileseemodel_user_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileseemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
