# Generated by Django 4.2.11 on 2024-03-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_userprofileseemodel_user_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileseemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
