# Generated by Django 4.2.11 on 2024-03-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userprofileseemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileseemodel',
            name='user_content',
        ),
    ]
