# Generated by Django 4.2.11 on 2024-03-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
