# Generated by Django 4.2.11 on 2024-03-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_comment_comment_subscriberscontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentuploud_model',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscribersContent',
        ),
    ]
