# Generated by Django 4.2.11 on 2024-03-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_contentuploud_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileseemodel',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contentuploud_model'),
        ),
    ]
