# Generated by Django 4.2.11 on 2024-03-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_userprofileseemodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileseemodel',
            name='content',
        ),
    ]
