# Generated by Django 4.2.11 on 2024-03-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_userprofileseemodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileseemodel',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.contentuploud_model'),
            preserve_default=False,
        ),
    ]
