# Generated by Django 4.2.11 on 2024-03-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_userprofileseemodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileseemodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
