# Generated by Django 4.2.11 on 2024-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_userprofileseemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileseemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
