# Generated by Django 4.2.11 on 2024-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_userprofileseemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileseemodel',
            name='meta_active',
            field=models.BooleanField(default=False),
        ),
    ]
