# Generated by Django 4.2.11 on 2024-03-21 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_getmeta_age_getmeta_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileseemodel',
            name='meta_active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_meta_activet_user', to='core.activemeta'),
        ),
    ]
