# Generated by Django 4.2.11 on 2024-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_userprofileseemodel_meta_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileseemodel',
            name='content',
        ),
        migrations.AddField(
            model_name='getmeta',
            name='face_photo',
            field=models.ImageField(default=1, upload_to='meta face/'),
            preserve_default=False,
        ),
    ]
