# Generated by Django 4.2.11 on 2024-03-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_userprofileseemodel_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activemeta',
            old_name='meta',
            new_name='metas',
        ),
    ]
